### ISSUE TITLE
Issue with an accent - Super Collider , Quarks

### ISSUE THREAD

**Issue by behaviorsynthwave** [supercollider/sc3-plugins#188] opened 2018-03-05 16:28 UTC
Im trying to install SuperDirt , Dirt Samples and some others with quark, but when i try to run "SuperDirt". it try to finds a route that din't exist. Adding to that the user name inside C:  in this win10 is " Aaron Sebástian".
Is it possible that the accent in this username may generate an error on plugings instalation?

**Comment by brianlheim** [comment] 2018-03-05 16:41
Yes, that's very possible. What versions of Supercollider and sc3-plugins are you using? I thought I had fixed all the issues with this but it looks like there are still some lurking. Can you please describe the issue in more detail, including full error messages you see?

**Comment by behaviorsynthwave** [comment] 2018-03-05 17:48
For sure,
In this case Im using:
SuperCollider-3.9.1-Windows-x64-VS
sc3-plugins-Version-3.9.1 wich includes ***img 1**
![img1](https://user-images.githubusercontent.com/37079273/36989762-ac3f34a6-2070-11e8-9eb1-1894c17dd14a.png)


Everything looks fine at include("SuperDirt")
But SuperDirt.start show up this message ***img2**
![img2](https://user-images.githubusercontent.com/37079273/36989925-1b580dea-2071-11e8-9b69-135f86c1aa3c.png)

" File 'C:\Users\Aaron Sebástian\AppData\Local\SuperCollider\downloaded-quarks\SuperDirt\classes\..\..\Dirt-Samples\yeah\021_Sound33.wav' could not be opened: System error : El sistema no puede encontrar la ruta especificada.


File 'C:\Users\Aaron Sebástian\AppData\Local\SuperCollider\downloaded-quarks\SuperDirt\classes\..\..\Dirt-Samples\yeah\022_Sound34.wav' could not be opened: System error : El sistema no puede encontrar la ruta especificada.


File 'C:\Users\Aaron Sebástian\AppData\Local\SuperCollider\downloaded-quarks\SuperDirt\classes\..\..\Dirt-Samples\yeah\023_Sound35.wav' could not be opened: System error : El sistema no puede encontrar la ruta especificada.


File 'C:\Users\Aaron Sebástian\AppData\Local\SuperCollider\downloaded-quarks\SuperDirt\classes\..\..\Dirt-Samples\yeah\024_Sound36.wav' could not be opened: System error : El sistema no puede encontrar la ruta especificada.


File 'C:\Users\Aaron Sebástian\AppData\Local\SuperCollider\downloaded-quarks\SuperDirt\classes\..\..\Dirt-Samples\yeah\025_Sound4.wav' could not be opened: System error : El sistema no puede encontrar la ruta especificada.


File 'C:\Users\Aaron Sebástian\AppData\Local\SuperCollider\downloaded-quarks\SuperDirt\classes\..\..\Dirt-Samples\yeah\026_Sound5.wav' could not be opened: System error : El sistema no puede encontrar la ruta especificada.


File 'C:\Users\Aaron Sebástian\AppData\Local\SuperCollider\downloaded-quarks\SuperDirt\classes\..\..\Dirt-Samples\yeah\027_Sound6.wav' could not be opened: System error : El sistema no puede encontrar la ruta especificada.


yeah (31) File 'C:\Users\Aaron Sebástian\AppData\Local\SuperCollider\downloaded-quarks\SuperDirt\classes\..\..\Dirt-Samples\yeah\028_Sound7.wav' could not be opened: System error : El sistema no puede encontrar la ruta especificada.


File 'C:\Users\Aaron Sebástian\AppData\Local\SuperCollider\downloaded-quarks\SuperDirt\classes\..\..\Dirt-Samples\yeah\029_Sound8.wav' could not be opened: System error : El sistema no puede encontrar la ruta especificada.



... file reading complete. Required 376 MB of memory.

File 'C:\Users\Aaron Sebástian\AppData\Local\SuperCollider\downloaded-quarks\SuperDirt\classes\..\..\Dirt-Samples\yeah\030_Sound9.wav' could not be opened: System error : El sistema no puede encontrar la ruta especificada.


SuperDirt: listening to Tidal on port 57120
*** ERROR: SynthDef dirt_delay2 not found
FAILURE IN SERVER /s_new SynthDef not found
*** ERROR: SynthDef dirt_delay2 not found
FAILURE IN SERVER /s_new SynthDef not found
"

This are just a part or a more large error messages as you can see in "Img2"


Also when i open Quarks its shows this message when i try to open the local path *Img3

![img3](https://user-images.githubusercontent.com/37079273/36990201-efc3e6da-2071-11e8-85d9-d917578deb05.png)

This also happens on SuperDirt , DirtSamples and Vowel.

and trying to find where is the following direction  i just find this
![img4](https://user-images.githubusercontent.com/37079273/36990651-6396344a-2073-11e8-97f5-445f904a9063.png)


looks like its trying to find 2 folders that dind't exist.

**Comment by jamshark70** [comment] 2018-03-06 01:58
Looks to me like one of two possible problems:

- The `..` ("go to parent") path specifiers might be getting corrupted internally. This seems unlikely because they appear in the post window correctly -- `classes\..\..\Dirt-Samples` -- but not in your copy/paste to github.

- Or, maybe Windows doesn't support `..` to navigate to the parent directory.

I don't know why superdirt is not using `.dirname` to navigate to the parent instead of the (possibly Unix-specific) `..`.

**Comment by brianlheim** [comment] 2018-03-06 02:29
@jamshark70 - `..` is not Unix-specific.

> they appear in the post window correctly -- `classes\..\..\Dirt-Samples` -- but not in your copy/paste to github.

This is because of the way GH-flavored markdown parses backslashes. `\..\..` in non-code text becomes \..\..

@behaviorsynthwave - if you can track down which calls in the SC class library specifically are producing these errors, I'd really appreciate it. I'm not familiar with SuperDirt so it's hard for me to tell which call those errors are coming from. If not I can look into this some other time. In the third screenshot (the one of the Quarks GUI) the accent is being incorrectly transcoded, which is a clue. Thanks for the robust report!

**Comment by brianlheim** [comment] 2018-03-06 03:08
@behaviorsynthwave - part of the problem is the space in your username. This is fixed by https://github.com/supercollider/supercollider/pull/2778, which I just re-opened.

**Comment by brianlheim** [comment] 2018-06-08 05:50
This is an issue in supercollider, not plugins. https://github.com/supercollider/supercollider/issues/3719

**Closed by brianlheim** 2018-06-08 05:50 UTC
