### ISSUE TITLE
Really weird, glitchy audio with JPverb and Greyhole

### ISSUE THREAD

**Issue by backseatviolist** [supercollider/sc3-plugins#59] opened 2016-01-05 05:40 UTC
Run the following and leave it running for a while:

    (
    { JPverb.ar(Saw.ar(100) * EnvGen.kr(Env.perc(0.01, 1), Impulse.kr(0))) * 0.1 }.play;
    { SinOsc.ar(440) * EnvGen.kr(Env.perc(0.01, 1), Impulse.kr(1)) * 0.1!2 }.play;
    )

Watch the CPU. For me, it stays at a consistent 7-8% for a while. After about one minute, it spikes to 50% and then quickly drops to less than 1%, and the audio from the *other* synth sounds weird and crackly.

This happens consistently when audio is fed into a JPverb or a Greyhole followed by a long stretch of complete silence. After the silence, all other audio output from SuperCollider sounds crackly. If audio is played to the reverb unit again, the audio returns to normal after a few seconds.

Even weirder, the crackliness does not seem to show up in Stethoscope, FreqScope, or s.record!

**Comment by jamshark70** [comment] 2016-01-05 06:56
Dollars to donuts it's a denormal-number problem.

**Comment by backseatviolist** [comment] 2016-01-05 07:07
This same problem happened with another reverb ugen I was writing myself. They have in common that they were written in FAUST, so this problem may ultimately stem from FAUST's lack of protection from denormals by default. Throwing in some equivalent of SC's `zapgremlins` will probably fix it.

**Comment by sonoro1234** [comment] 2016-01-05 15:39
denormal handling is now handled in audio driver callback.
Is scsynth an old version?
  ----- Original Message -----

**Comment by danstowell** [comment] 2016-01-05 15:48
@sonoro1234 if a ugen creates denormals internally, and performs calculations with them, the ugen itself needs to zap them

**Comment by sonoro1234** [comment] 2016-01-05 15:55
sc_SetDenormalFlags(); is used inside audio driver callback but it means that "all number processing" in this thread make denormals go to zero

**Comment by sonoro1234** [comment] 2016-01-05 16:03
sc_SetDenormalFlags is defined in SC_World.cpp:165 but only for __SSE__ or __SSE2__ 
I dont know which architectures dont have that

**Comment by danstowell** [comment] 2016-01-05 16:11
@sonoro1234 ah of course, sorry.

**Comment by backseatviolist** [comment] 2016-01-05 18:34
@sonoro1234 I have experienced this error in both 3.6 and 3.7alpha1. Since this seems architecture-dependent, I am using 32-bit Ubuntu.

**Comment by timblechmann** [comment] 2016-01-06 09:23
these days all x86 CPUs without SSE2 should be better off in a museum. imho, sse2 should be the minimum requirement these days. someone might want to adapt the compiler flags. also, there are no 64bit x86 cpus without SSE2, so compilers will enable it by default.

**Comment by sonoro1234** [comment] 2016-01-07 15:17
@backseatviolist i am not sure when denormal handling Was merged . Please try with last github

**Comment by backseatviolist** [comment] 2016-01-08 01:03
@sonoro1234 The problem occurs with the latest 3.7. crucialfelix [recommended](https://github.com/supercollider/supercollider/pull/1758#issuecomment-162447463) that I use the 3.7 branch instead of the master (which currently doesn't compile for me).

**Comment by sonoro1234** [comment] 2016-01-08 21:53
@backseatviolist  denormal handling seems ok in 3.7 branch. This should not be happenning. More investigation is needed!!

**Comment by backseatviolist** [comment] 2016-01-09 03:36
@sonoro1234 Should someone file an issue in the main supercollider repo? Clearly the problem here isn't the plugins themselves.

**Comment by sonoro1234** [comment] 2016-01-11 13:22
@backseatviolist  I could try the sample but could not reproduce the issue. First you could try with CheckBadValues to reasure and then file the issue.

**Comment by sonoro1234** [comment] 2016-01-11 14:21
@backseatviolist My JPverb parameters were not right. I can reproduce now the CPU issue but CheckBadValues dont show denormals. I am lost!!

**Comment by backseatviolist** [comment] 2016-01-11 14:24
@sonoro1234 It is a REALLY bizarre bug. SuperCollider doesn't seem to record or detect the denormals. (Even weirder, the glitched audio seems to change when I plug or unplug my laptop's power source!)

**Comment by sonoro1234** [comment] 2016-01-11 14:50
I would say that glitched audio is just a consequence of CPU load. If you free the synth with JPverb CPU goes down and glitch dissapears.

**Comment by backseatviolist** [comment] 2016-01-11 15:24
Are you sure? The CPU meter only reports about 1% when the glitches happen.

**Comment by sonoro1234** [comment] 2016-01-11 16:06
Not in my computer. always at 400%
Check with system CPU meter and not with scide CPU meter.

**Comment by backseatviolist** [comment] 2016-01-12 00:14
You're right, scsynth gobbles up 13-14% CPU and JACK is reporting a bunch of xruns.

**Comment by sonoro1234** [comment] 2016-01-12 17:01
@backseatviolist 
Investigation results:
On 32 bits architectures -mfpmath=sse gcc compiler flag must be set to force simd on all operations.
Try to compile JPverb with this flags (set it in CMakeList.txt)

**Comment by backseatviolist** [comment] 2016-01-13 00:40
With that flag, `make` gives me a bunch of warnings saying "SSE instruction set disabled, using 387 arithmetics [enabled by default]". The bug is the same.

**Comment by backseatviolist** [comment] 2016-01-13 01:27
@sonoro1234 `-msse -msse2 -mfpmath=sse` seems to work.

**Comment by sonoro1234** [comment] 2016-01-13 15:28
I asumed that -msse and -msse2 were already set, which is not the case. So, thanks to denormals, we have discovered that this flags should be setted in sc3-plugings. ( a lot of things will be faster)
I will make a pull request.

**Comment by sonoro1234** [comment] 2016-01-13 16:19
PR#63 is made. There is not speed increase but denormal problem dissapeared.
This issue can be closed.

**Closed** 2016-01-14 23:17 UTC

**Comment by LFSaw** [comment] 2016-01-16 10:00
Oh, wow! It seems that being offline from github for 2 weeks makes magic things happen! thanks so much for all the investigations!
